-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_log
(
    log_id serial NOT NULL,
    table_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    record_id integer NOT NULL,
    action character varying(10) COLLATE pg_catalog."default" NOT NULL,
    old_values jsonb,
    new_values jsonb,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_id integer,
    CONSTRAINT audit_log_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    client_id serial NOT NULL,
    user_id integer NOT NULL,
    address text COLLATE pg_catalog."default",
    date_of_birth date,
    sex character varying(6) COLLATE pg_catalog."default",
    CONSTRAINT clients_pkey PRIMARY KEY (client_id),
    CONSTRAINT clients_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.couriers
(
    courier_id serial NOT NULL,
    user_id integer NOT NULL,
    active boolean DEFAULT true,
    CONSTRAINT couriers_pkey PRIMARY KEY (courier_id),
    CONSTRAINT couriers_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.couriers_vehicles
(
    courier_id integer NOT NULL,
    vehicle_id integer NOT NULL,
    assigned_at timestamp without time zone,
    unassigned_at timestamp without time zone,
    CONSTRAINT couriers_vehicles_pkey PRIMARY KEY (courier_id, vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.deliveries
(
    delivery_id serial NOT NULL,
    order_id integer NOT NULL,
    courier_id integer NOT NULL,
    route_id integer NOT NULL,
    location_id integer NOT NULL,
    actual_delivery_datetime timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT deliveries_pkey PRIMARY KEY (delivery_id)
);

CREATE TABLE IF NOT EXISTS public.delivery_coordinates
(
    delivery_id integer,
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT delivery_coordinates_delivery_id_key UNIQUE (delivery_id)
);

CREATE TABLE IF NOT EXISTS public.items
(
    item_id serial NOT NULL,
    item_name character varying(100) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default",
    price numeric(9, 2),
    weight_kg numeric(6, 2),
    length_cm numeric(6, 2),
    width_cm numeric(6, 2),
    height_cm numeric(6, 2),
    CONSTRAINT items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.location_types
(
    location_type_id serial NOT NULL,
    location_type character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT location_types_pkey PRIMARY KEY (location_type_id)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    location_id serial NOT NULL,
    location_type_id integer NOT NULL,
    address character varying(500) COLLATE pg_catalog."default",
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id serial NOT NULL,
    client_id integer NOT NULL,
    order_id integer NOT NULL,
    status_id integer NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_read boolean DEFAULT false,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_id integer NOT NULL,
    item_id integer NOT NULL,
    ordered_quantity integer,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    client_id integer NOT NULL,
    status_id integer NOT NULL,
    total_weight numeric(10, 2),
    total_price numeric(12, 2),
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id serial NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.route_points
(
    route_id integer NOT NULL,
    sequence_num integer NOT NULL,
    location_id integer NOT NULL,
    expected_arrival_time timestamp without time zone,
    actual_arrival_time timestamp without time zone,
    CONSTRAINT route_points_pkey PRIMARY KEY (route_id, sequence_num)
);

CREATE TABLE IF NOT EXISTS public.routes
(
    route_id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    total_distance_km numeric(6, 2),
    total_time_min integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT routes_pkey PRIMARY KEY (route_id)
);

CREATE TABLE IF NOT EXISTS public.statuses
(
    status_id serial NOT NULL,
    status_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT statuses_pkey PRIMARY KEY (status_id),
    CONSTRAINT statuses_status_name_key UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS public.store_stock
(
    location_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT store_stock_pkey PRIMARY KEY (location_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    vehicle_id serial NOT NULL,
    type character varying(50) COLLATE pg_catalog."default",
    license_plate character varying(20) COLLATE pg_catalog."default",
    capacity numeric(6, 2),
    status character varying(30) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id),
    CONSTRAINT vehicles_license_plate_key UNIQUE (license_plate)
);

ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clients
    ADD CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS clients_user_id_key
    ON public.clients(user_id);


ALTER TABLE IF EXISTS public.couriers
    ADD CONSTRAINT couriers_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS couriers_user_id_key
    ON public.couriers(user_id);


ALTER TABLE IF EXISTS public.couriers_vehicles
    ADD CONSTRAINT couriers_vehicles_courier_id_fkey FOREIGN KEY (courier_id)
    REFERENCES public.couriers (courier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.couriers_vehicles
    ADD CONSTRAINT couriers_vehicles_vehicle_id_fkey FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (vehicle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.deliveries
    ADD CONSTRAINT deliveries_courier_id_fkey FOREIGN KEY (courier_id)
    REFERENCES public.couriers (courier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_deliveries_courier_id
    ON public.deliveries(courier_id);


ALTER TABLE IF EXISTS public.deliveries
    ADD CONSTRAINT deliveries_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.deliveries
    ADD CONSTRAINT deliveries_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_deliveries_order_id
    ON public.deliveries(order_id);


ALTER TABLE IF EXISTS public.deliveries
    ADD CONSTRAINT deliveries_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.routes (route_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_deliveries_route_id
    ON public.deliveries(route_id);


ALTER TABLE IF EXISTS public.delivery_coordinates
    ADD CONSTRAINT delivery_coordinates_delivery_id_fkey FOREIGN KEY (delivery_id)
    REFERENCES public.deliveries (delivery_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS delivery_coordinates_delivery_id_key
    ON public.delivery_coordinates(delivery_id);


ALTER TABLE IF EXISTS public.locations
    ADD CONSTRAINT locations_location_type_id_fkey FOREIGN KEY (location_type_id)
    REFERENCES public.location_types (location_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.statuses (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_client_id
    ON public.orders(client_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.statuses (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_status_id
    ON public.orders(status_id);


ALTER TABLE IF EXISTS public.route_points
    ADD CONSTRAINT route_points_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_route_points_location_id
    ON public.route_points(location_id);


ALTER TABLE IF EXISTS public.route_points
    ADD CONSTRAINT route_points_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.routes (route_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_route_points_route_id
    ON public.route_points(route_id);


ALTER TABLE IF EXISTS public.store_stock
    ADD CONSTRAINT store_stock_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.store_stock
    ADD CONSTRAINT store_stock_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;